from e_database import importer

def create_all():    
    importer.create_category_list_table()
    importer.create_dialogue_list_table()
    importer.create_my_question_table()
    importer.create_project_list_table()
    importer.create_question_list_table()
    importer.create_request_question_table('chatbot_tft', 'fund')
    importer.create_right_answer_table()
    importer.create_schedule_table()
    importer.create_synonym_list_table()
    importer.create_tag_list_table()
    importer.create_user_info_table()
    importer.create_voca_table()
    importer.create_vocab_dec_table()
    importer.create_vocab_enc_table()
    importer.create_vocab_tag_table()
    importer.create_wrong_answer_table()
    importer.create_compression_tag_table('chatbot_tft', 'fund')
    importer.create_answer_builder_table('chatbot_tft', 'fund')
    importer.create_question_builder_table('chatbot_tft', 'fund')
    importer.create_question_fragment_builder_table('chatbot_tft', 'fund')
    importer.create_training_config_list_table('chatbot_tft', 'fund')
    importer.create_chatbot_config_list_table('chatbot_tft', 'fund')
